### ISSUE TITLE
slayterdev.github.io is Gone?

### ISSUE THREAD

**Issue by rebelwcause** [duckduckgo/tracker-radar-wiki#54]
Github pages website
https://slayterdev.github.io/tracker-radar-wiki/
no longer exists?
Get 404, There isn't a GitHub Pages site here. ?
(Tried Sept 26/2023 and Sept 27/2023)
Is this intended?

**Comment by SlayterDev** [comment]
Thanks for the notification. Some recent automation caused an issue. The site is being redeployed and should be available shortly.
