### ISSUE TITLE
Entities that include special chars in their names break links

### ISSUE THREAD

**Issue by dharb** [duckduckgo/tracker-radar-wiki#6]
For Windows compat, we had to filter out certain special chars from filenames, making them not exactly 1 to 1 with entity names. This is causing some broken links (eg clicking Adform A/S - 6.34% on https://slayterdev.github.io/tracker-radar-wiki/top100.html doesn't work).

I bet we could use the same regex I used to remove these special chars to fix these links:
`entityName.replace(/\/|!|"|:|>|<|\/|\\|\||\?|\*/g, '')`

**Comment by kdzwinel** [comment]
Thanks for that regex. It should be fixed now for most links including top100 (I might have missed some).
